kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang
  commands:
  - echo "go"

- name: frontend
  image: node
  commands:
  - node -v

- name: notify
  image: node
  depends_on:
  - frontend
  - backend
  commands:
  - node -v
