kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang
  commands:
  - go

- name: frontend
  image: node
  commands:
  - node -v

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: webhook
  depends_on:
  - frontend
  - backend
